# Makefile for CSVParserWithTests
# made by Sarah Strickman sxs4599


prime: csv.c
	gcc -o test -g -Wall csv.c unit_tests.c
	gcc -o csv -g -Wall csv.c unit_tests.c

#	./csv<food.csv
	./test

clean: 
	rm test
	rm csv
